# Generated by Django 2.2.7 on 2019-11-09 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inih', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inih',
            old_name='texto',
            new_name='descr1',
        ),
        migrations.AddField(
            model_name='inih',
            name='descr2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
