# Generated by Django 2.2.7 on 2019-11-13 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inih', '0002_auto_20191109_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='servh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descr1', models.TextField()),
                ('fecha_c', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_p', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
