# Generated by Django 2.2.7 on 2019-11-13 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inih', '0003_servh'),
    ]

    operations = [
        migrations.DeleteModel(
            name='servh',
        ),
    ]
