# Generated by Django 2.2.7 on 2019-11-14 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inih', '0004_delete_servh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inih',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Nombre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrem', models.CharField(max_length=50)),
                ('subm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu', to='inih.menu')),
            ],
        ),
    ]
