# Generated by Django 2.2.7 on 2019-11-16 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inih', '0006_auto_20191114_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='servh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descr', models.TextField()),
                ('status', models.BooleanField(choices=[(0, 'Inactive'), (1, 'Active')], default=0)),
                ('fecha_c', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_p', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servh', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
