# Generated by Django 2.2.7 on 2019-11-17 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inih', '0008_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='fecha_c',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='archivo',
            name='fecha_p',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
