# Generated by Django 2.2.7 on 2019-11-17 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inih', '0011_auto_20191117_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='habh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descr', models.TextField()),
                ('status', models.CharField(choices=[(0, 'Inactive'), (1, 'Desocupada'), (2, 'Ocupada'), (3, 'Reservada')], default=1, max_length=2)),
                ('fecha_c', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_p', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
